# Generated by Django 3.1 on 2021-08-07 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category_of_todo',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField()),
                ('check', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todo')),
            ],
            options={
                'ordering': ['date_begin'],
            },
        ),
    ]
