# Generated by Django 3.1 on 2021-08-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210807_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
